name: flutcn
description: A CLI tool for adding pre-styled Flutter UI components to existing projects
version: 0.1.0
homepage: https://github.com/Sums-shadow/flutcn

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  yaml: ^3.1.2
  ansicolor: ^2.0.2
  cli_util: ^0.4.0
  logger: ^2.5.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6

executables:
  flutcn: flutcn